create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,email text,display_name text,status text not null default 'pending' check(status in('pending','approved','rejected')),is_admin boolean not null default false,created_at timestamptz default now());
create table if not exists public.stories (id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete cascade,title text not null,genre text default 'Giả tưởng',description text default '',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.chapters (id uuid primary key default gen_random_uuid(),story_id uuid not null references public.stories(id) on delete cascade,number int not null,title text not null,content text default '',word_count int default 0,created_at timestamptz default now(),updated_at timestamptz default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer as $$ begin insert into public.profiles(id,email,display_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'display_name','User')); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security; alter table public.stories enable row level security; alter table public.chapters enable row level security;
create policy "profile self" on public.profiles for select using(auth.uid()=id or exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin));
create policy "stories owner" on public.stories for all using(owner_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin)) with check(owner_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin));
create policy "chapters owner" on public.chapters for all using(exists(select 1 from public.stories s where s.id=story_id and (s.owner_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin)))) with check(exists(select 1 from public.stories s where s.id=story_id and (s.owner_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin))));
create or replace function public.admin_set_user_status(target_id uuid,new_status text) returns void language plpgsql security definer as $$ begin if not exists(select 1 from public.profiles where id=auth.uid() and is_admin) then raise exception 'not admin'; end if; update public.profiles set status=new_status where id=target_id; end; $$;
-- Sau khi đăng ký user đầu tiên, chạy dòng dưới với ID của tài khoản mày để biến nó thành Admin:
-- update public.profiles set is_admin=true,status='approved' where email='EMAIL_CUA_MAY';
