import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './style.css';

const supabase = import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY
  ? createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY) : null;
const STORE='storyforge_pro_total_';
const icons={dashboard:'⌂',chapters:'▤',characters:'♙',world:'◇',timeline:'◷',canon:'◆',notes:'✎',ai:'✦',admin:'♛'};
const labels={dashboard:'Tổng quan',chapters:'Chương',characters:'Nhân vật',world:'Thế giới',timeline:'Dòng thời gian',canon:'Canon',notes:'Ghi chú',ai:'Trợ lý AI',admin:'Quản trị'};
const navGroups=[{label:'SÁNG TÁC',items:['dashboard','chapters']},{label:'XÂY DỰNG TRUYỆN',items:['characters','world','timeline','canon','notes']},{label:'AI',items:['ai']}];

const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(STORE+k))??f}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem(STORE+k,JSON.stringify(v))}catch{}};
const words=(s='')=>s.trim()?s.trim().split(/\s+/).length:0;
const chars=(s='')=>s.length;
const fmt=d=>{try{return new Date(d).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}catch{return '—'}};
const short=(s='',n=150)=>s.length>n?s.slice(0,n)+'…':s;

function Brand(){return <div className="brand"><div className="logoMark">✦</div><div><strong>StoryForge</strong><small>Writing Studio</small></div></div>}
function Loading({text='Đang tải StoryForge…'}){return <div className="loadingScreen"><div className="logoMark">✦</div><h2>{text}</h2><div className="loader"/></div>}
function Auth({onDone}){
  const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  const submit=async()=>{if(!supabase)return setMsg('Chưa cấu hình Supabase.');if(!email.trim()||!pass)return setMsg('Vui lòng nhập email và mật khẩu.');if(mode==='signup'&&!name.trim())return setMsg('Vui lòng nhập tên hiển thị.');setBusy(true);setMsg('');try{
    if(mode==='login'){const r=await supabase.auth.signInWithPassword({email:email.trim(),password:pass});if(r.error)throw r.error;await onDone(r.data.user)}
    else {const r=await supabase.auth.signUp({email:email.trim(),password:pass,options:{data:{display_name:name.trim()}}});if(r.error)throw r.error;if(r.data.session&&r.data.user){await onDone(r.data.user)}else setMsg('Đăng ký thành công. Hãy chờ Admin duyệt quyền truy cập.')}
  }catch(e){setMsg(e?.message||'Có lỗi xảy ra.')}finally{setBusy(false)}};
  return <div className="authScreen"><div className="authBackdrop"/><div className="authCard"><Brand/><span className="eyebrow">PRIVATE WRITING STUDIO</span><h1>{mode==='login'?'Tiếp tục câu chuyện.':'Bắt đầu không gian sáng tác.'}</h1><p className="authLead">Một nơi để viết, xây dựng thế giới và hội ý với AI mà không làm mất chất riêng của tác giả.</p>
    {mode==='signup'&&<label>Tên hiển thị<input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên tác giả"/></label>}
    <label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>
    <label>Mật khẩu<input type="password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="••••••••"/></label>
    <button className="primary wide" disabled={busy} onClick={submit}>{busy?'Đang xử lý…':mode==='login'?'Đăng nhập':'Tạo tài khoản'}</button>
    {msg&&<div className="notice">{msg}</div>}<button className="linkBtn center" onClick={()=>{setMsg('');setMode(mode==='login'?'signup':'login')}}>{mode==='login'?'Chưa có tài khoản? Đăng ký':'Đã có tài khoản? Đăng nhập'}</button>
  </div></div>
}
async function getProfile(){if(!supabase)return null;const r=await supabase.rpc('get_my_profile');return r.data||null}
function Pending(){return <div className="authScreen"><div className="authCard pending"><div className="pendingIcon">◷</div><span className="eyebrow">ACCESS REQUEST</span><h1>Đang chờ Admin duyệt</h1><p>Tài khoản của bạn đã được ghi nhận. Khi Admin duyệt, bạn sẽ có toàn bộ không gian StoryForge.</p><div className="pendingSteps"><span>✓ Đã đăng ký</span><span className="current">◷ Chờ duyệt</span><span>○ Truy cập</span></div><button className="ghost wide" onClick={()=>supabase.auth.signOut()}>Đăng xuất</button></div></div>}

function App(){
  const [user,setUser]=useState(null),[prof,setProf]=useState(null),[ready,setReady]=useState(false);
  const loadUser=async u=>{if(!u){setUser(null);setProf(null);return}setUser(u);setProf(await getProfile())};
  useEffect(()=>{if(!supabase){setReady(true);return}let alive=true;supabase.auth.getSession().then(async({data:{session}})=>{if(!alive)return;if(session?.user)await loadUser(session.user);setReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(!alive)return;if(s?.user)setTimeout(()=>loadUser(s.user),0);else{setUser(null);setProf(null)}});return()=>{alive=false;subscription.unsubscribe()}},[]);
  if(!ready)return <Loading/>; if(!user)return <Auth onDone={loadUser}/>; if(!prof)return <Loading text="Đang kiểm tra quyền truy cập…"/>; if(prof.status!=='approved'&&!prof.is_admin)return <Pending/>; return <Studio user={user} prof={prof}/>;
}

function Studio({user,prof}){
  const saved=load('workspace_'+user.id,{tab:'dashboard',storyId:null,chapterId:null}),[tab,setTab]=useState(saved.tab),[stories,setStories]=useState([]),[story,setStory]=useState(null),[chapters,setChapters]=useState([]),[chapter,setChapter]=useState(null),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[mobile,setMobile]=useState(false);
  const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2800)};
  const loadStories=async()=>{const r=await supabase.from('stories').select('*').order('updated_at',{ascending:false});if(!r.error)setStories(r.data||[]);else notify(r.error.message)};
  const loadChapters=async id=>{if(!id){setChapters([]);return}const r=await supabase.from('chapters').select('*').eq('story_id',id).order('number',{ascending:true});if(!r.error)setChapters(r.data||[]);else notify(r.error.message)};
  useEffect(()=>{loadStories()},[]);
  useEffect(()=>{if(!stories.length||story)return;const s=saved.storyId?stories.find(x=>x.id===saved.storyId):null;if(s)setStory(s)},[stories]);
  useEffect(()=>{loadChapters(story?.id)},[story?.id]);
  useEffect(()=>{if(!story||!saved.chapterId||chapter)return;const c=chapters.find(x=>x.id===saved.chapterId);if(c)setChapter(c)},[chapters,story]);
  useEffect(()=>{save('workspace_'+user.id,{tab,storyId:story?.id||null,chapterId:chapter?.id||null})},[tab,story?.id,chapter?.id]);
  const openStory=s=>{setStory(s);setChapter(null);setTab('chapters');setMobile(false)};
  const navigate=k=>{setTab(k);setMobile(false)};
  const createStory=async f=>{const r=await supabase.from('stories').insert({owner_id:user.id,title:f.title.trim(),genre:f.genre,description:f.description.trim(),cover_url:f.cover_url.trim(),status:'writing'}).select().single();if(r.error)return notify(r.error.message);setStories(x=>[r.data,...x]);setStory(r.data);setChapter(null);setModal(null);setTab('chapters');notify('Đã tạo truyện.')};
  const updateStory=async f=>{const r=await supabase.from('stories').update({title:f.title.trim(),genre:f.genre,description:f.description.trim(),cover_url:f.cover_url.trim(),status:f.status}).eq('id',story.id).select().single();if(r.error)return notify(r.error.message);setStory(r.data);setStories(x=>x.map(s=>s.id===r.data.id?r.data:s));setModal(null);notify('Đã lưu thông tin truyện.')};
  const deleteStory=async s=>{if(!confirm(`Xóa “${s.title}” và toàn bộ dữ liệu liên quan?`))return;const r=await supabase.from('stories').delete().eq('id',s.id);if(r.error)return notify(r.error.message);setStories(x=>x.filter(a=>a.id!==s.id));if(story?.id===s.id){setStory(null);setChapter(null);setTab('dashboard')}notify('Đã xóa truyện.')};
  const nav=prof.is_admin?[...navGroups,{label:'QUẢN TRỊ',items:['admin']}]:navGroups;
  return <div className="app"><div className={'mobileShade '+(mobile?'show':'')} onClick={()=>setMobile(false)}/><aside className={mobile?'open':''}><Brand/><button className="mobileClose" onClick={()=>setMobile(false)}>×</button>
    <div className="activeStory">{story?<><div className="miniCover" style={story.cover_url?{backgroundImage:`url(${story.cover_url})`}:undefined}>{!story.cover_url&&'✦'}</div><div><b>{story.title}</b><small>{chapters.length} chương · {chapters.reduce((a,c)=>a+(c.word_count||words(c.content)),0).toLocaleString('vi-VN')} từ</small></div></>:<div><b>Thư viện sáng tác</b><small>Chọn một truyện để bắt đầu</small></div>}</div>
    <nav>{nav.map(g=><div className="navGroup" key={g.label}><span className="navLabel">{g.label}</span>{g.items.map(k=><button key={k} className={tab===k?'active':''} onClick={()=>navigate(k)}><span>{icons[k]}</span>{labels[k]}</button>)}</div>)}</nav>
    <div className="account"><div className="avatar">{(prof.display_name||'U').slice(0,1).toUpperCase()}</div><div><b>{prof.display_name||'Tác giả'}</b><small>{prof.is_admin?'Admin':'Tác giả'}</small></div><button className="logout" onClick={()=>supabase.auth.signOut()}>↪</button></div></aside>
    <main><header className="topbar"><button className="menuBtn" onClick={()=>setMobile(true)}>☰</button><div className="topTitle"><span className="eyebrow">STORYFORGE / {labels[tab].toUpperCase()}</span><h1>{labels[tab]}</h1></div><div className="topActions"><span className="sync">● Cloud synced</span>{tab!=='dashboard'&&<button className="ghost desktopOnly" onClick={()=>navigate('dashboard')}>← Tổng quan</button>}<button className="primary" onClick={()=>setModal('createStory')}>＋ Truyện mới</button></div></header>
      <div className="page">{tab==='dashboard'&&<Dashboard stories={stories} story={story} chapters={chapters} onSelect={openStory} onNew={()=>setModal('createStory')} onEdit={()=>story?setModal('editStory'):notify('Hãy chọn một truyện.')} onDelete={deleteStory}/>} {tab==='chapters'&&<ChapterModule story={story} chapters={chapters} chapter={chapter} setChapter={setChapter} refresh={loadChapters} notify={notify}/>} {['characters','world','timeline','canon','notes'].includes(tab)&&<DataModule story={story} type={tab} notify={notify}/>} {tab==='ai'&&<AIHub story={story} chapter={chapter} user={user} notify={notify}/>} {tab==='admin'&&prof.is_admin&&<Admin notify={notify}/>}</div>
    </main>{toast&&<div className="toast">✓ {toast}</div>}{modal==='createStory'&&<StoryModal title="Tạo truyện mới" onClose={()=>setModal(null)} onSave={createStory}/>} {modal==='editStory'&&story&&<StoryModal title="Thông tin truyện" initial={story} onClose={()=>setModal(null)} onSave={updateStory}/>}</div>
}

function Dashboard({stories,story,chapters,onSelect,onNew,onEdit,onDelete}){
  const [q,setQ]=useState(''); const filtered=stories.filter(s=>(s.title+' '+(s.description||'')+' '+(s.genre||'')).toLowerCase().includes(q.toLowerCase()));
  const total=stories.reduce((a,s)=>a+(s._words||0),0);
  return <section className="dashboard"><div className="welcomeHero"><div><span className="eyebrow">YOUR WRITING SPACE</span><h2>Viết điều chỉ<br/><em>bạn có thể kể.</em></h2><p>Truyện, thế giới, nhân vật và AI cùng ở một nơi. Bạn quyết định câu chuyện; StoryForge giữ mọi thứ có tổ chức.</p><div className="heroBtns"><button className="primary" onClick={onNew}>✦ Tạo truyện mới</button>{story&&<button className="ghost" onClick={()=>onSelect(story)}>Tiếp tục viết →</button>}</div></div><div className="heroVisual"><div className="heroGlow"/><div className="heroQuote">“Câu chuyện tốt bắt đầu từ một trang trắng.”<small>— StoryForge</small></div><div className="heroBadge">✦ AI<br/><small>theo Canon</small></div></div></div>
    <div className="stats"><div><span>Truyện</span><b>{stories.length}</b></div><div><span>Chương</span><b>{chapters.length}</b></div><div><span>Tổng từ</span><b>{total.toLocaleString('vi-VN')}</b></div><div><span>Không gian</span><b>Cloud</b></div></div>
    <div className="sectionHead"><div><span className="eyebrow">LIBRARY</span><h2>Thư viện truyện</h2><p className="muted">Mỗi truyện là một workspace riêng.</p></div><div className="searchBox">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm truyện…"/></div></div>
    {!filtered.length?<div className="empty big"><div className="emptyArt">✦</div><h3>{stories.length?'Không tìm thấy truyện':'Câu chuyện đầu tiên đang chờ bạn.'}</h3><p>{stories.length?'Thử từ khóa khác.':'Tạo một truyện, thêm bìa và bắt đầu từ chương đầu tiên.'}</p><button className="primary" onClick={onNew}>{stories.length?'Tạo truyện mới':'Tạo truyện đầu tiên'}</button></div>:<div className="storyGrid">{filtered.map(s=><article className={'storyCard '+(story?.id===s.id?'selected':'')} key={s.id} onClick={()=>onSelect(s)}><div className="cover" style={s.cover_url?{backgroundImage:`linear-gradient(180deg,transparent 30%,rgba(5,5,12,.95)),url(${s.cover_url})`}:undefined}>{!s.cover_url&&<div className="coverFallback"><span>✦</span><small>STORYFORGE</small></div>}<span className="coverStatus">{s.status==='completed'?'Hoàn thành':s.status==='paused'?'Tạm dừng':'Đang viết'}</span></div><div className="storyInfo"><div className="storyTop"><span className="tag">{s.genre||'Khác'}</span><span>{fmt(s.updated_at)}</span></div><h3>{s.title}</h3><p>{short(s.description||'Chưa có mô tả.',120)}</p><div className="storyMeta"><span>⌁ Workspace</span><span>{s._words||0} từ</span></div><div className="cardActions"><button onClick={e=>{e.stopPropagation();onSelect(s)}}>Viết tiếp</button><button className="iconBtn" onClick={e=>{e.stopPropagation();onEdit(s)}}>✎</button><button className="iconBtn danger" onClick={e=>{e.stopPropagation();onDelete(s)}}>×</button></div></div></article>)}</div>}</section>
}

function ChapterModule({story,chapters,chapter,setChapter,refresh,notify}){
  const [modal,setModal]=useState(false); if(!story)return <EmptySelect title="Chọn một truyện để viết" text="Vào Tổng quan để chọn truyện hoặc tạo một truyện mới."/>;
  if(chapter)return <Editor story={story} chapter={chapter} chapters={chapters} setChapter={setChapter} refresh={refresh} notify={notify}/>;
  const create=async f=>{const n=(chapters.reduce((m,c)=>Math.max(m,c.number||0),0))+1;const r=await supabase.from('chapters').insert({story_id:story.id,number:n,title:f.title.trim()||`Chương ${n}`,content:'',word_count:0}).select().single();if(r.error)return notify(r.error.message);setChapter(r.data);refresh();setModal(false);notify('Đã tạo chương mới.')};
  return <section><div className="sectionHead"><div><span className="eyebrow">{story.title}</span><h2>Chương</h2><p className="muted">{chapters.length} chương · {chapters.reduce((a,c)=>a+(c.word_count||words(c.content)),0).toLocaleString('vi-VN')} từ</p></div><button className="primary" onClick={()=>setModal(true)}>＋ Chương mới</button></div>
    {!chapters.length?<div className="empty big"><div className="emptyArt">✍</div><h3>Trang đầu tiên đang chờ bạn.</h3><p>Viết trực tiếp, tự lưu và gọi AI khi thật sự cần.</p><button className="primary" onClick={()=>setModal(true)}>Bắt đầu chương 1</button></div>:<div className="chapterList">{chapters.map(c=><button className="chapterRow" key={c.id} onClick={()=>setChapter(c)}><div className="chapterNo">{String(c.number).padStart(2,'0')}</div><div><b>{c.title}</b><small>{c.word_count||words(c.content)} từ · Cập nhật {fmt(c.updated_at)}</small></div><span>→</span></button>)}</div>}
    {modal&&<SimpleModal title="Chương mới" onClose={()=>setModal(false)}><ChapterForm onSave={create} onCancel={()=>setModal(false)}/></SimpleModal>}
  </section>
}
function Editor({story,chapter,chapters,setChapter,refresh,notify}){
  const [title,setTitle]=useState(chapter.title),[content,setContent]=useState(chapter.content||''),[saving,setSaving]=useState(false),[savedAt,setSavedAt]=useState(chapter.updated_at),[font,setFont]=useState(load('editor_font','Be Vietnam Pro')),[size,setSize]=useState(load('editor_size',19)),[focus,setFocus]=useState(false),[versions,setVersions]=useState([]),[showVersions,setShowVersions]=useState(false);
  useEffect(()=>{setTitle(chapter.title);setContent(chapter.content||'');setSavedAt(chapter.updated_at)},[chapter.id]);
  const persist=async(makeVersion=false)=>{setSaving(true);if(makeVersion){await supabase.from('chapter_versions').insert({chapter_id:chapter.id,title,content,word_count:words(content)})}const r=await supabase.from('chapters').update({title:title.trim()||chapter.title,content,word_count:words(content)}).eq('id',chapter.id).select().single();setSaving(false);if(r.error){notify(r.error.message);return false}setSavedAt(r.data.updated_at);setChapter(r.data);refresh();return true};
  useEffect(()=>{const t=setTimeout(()=>{if(title!==chapter.title||content!==chapter.content)persist(false)},1100);return()=>clearTimeout(t)},[title,content]);
  const loadVersions=async()=>{const r=await supabase.from('chapter_versions').select('*').eq('chapter_id',chapter.id).order('created_at',{ascending:false}).limit(30);if(!r.error)setVersions(r.data||[]);setShowVersions(true)};
  const restore=v=>{if(!confirm('Khôi phục phiên bản này vào bản thảo hiện tại?'))return;setTitle(v.title);setContent(v.content);setShowVersions(false);notify('Đã nạp phiên bản. Hãy kiểm tra rồi tiếp tục viết.')};
  const goPrev=()=>{const i=chapters.findIndex(c=>c.id===chapter.id);if(i>0)setChapter(chapters[i-1])};const goNext=()=>{const i=chapters.findIndex(c=>c.id===chapter.id);if(i<chapters.length-1)setChapter(chapters[i+1])};
  const [showAI,setShowAI]=useState(false);
  return <div className={'editorShell '+(focus?'focusMode':'')}><div className="editorTop"><button className="backLink" onClick={()=>setChapter(null)}>← Các chương</button><div className="editorTitle"><span>{story.title}</span><b>{saving?'Đang lưu…':`Đã lưu ${savedAt?fmt(savedAt):''}`}</b></div><div className="editorTools"><button className="ghost" onClick={()=>{setFont(font==='Be Vietnam Pro'?'Literata':'Be Vietnam Pro');save('editor_font',font==='Be Vietnam Pro'?'Literata':'Be Vietnam Pro')}}>Aa {font==='Literata'?'Literata':'Be Vietnam'}</button><button className="ghost" onClick={()=>{const n=size>=23?17:size+2;setSize(n);save('editor_size',n)}}>{size}px</button><button className="ghost" onClick={()=>persist(true)}>＋ Phiên bản</button><button className="ghost" onClick={loadVersions}>◷ Lịch sử</button><button className={showAI?'primary':'ghost'} onClick={()=>setShowAI(!showAI)}>✦ Hội ý AI</button><button className="primary" onClick={()=>setFocus(!focus)}>{focus?'Thu gọn':'⌗ Tập trung'}</button></div></div>
    <div className={'editorLayout '+(showAI?'withAI':'')}><aside className="chapterRail"><div className="railHead"><span>CHƯƠNG</span><b>{String(chapter.number).padStart(2,'0')}</b></div>{chapters.map(c=><button key={c.id} className={c.id===chapter.id?'active':''} onClick={()=>setChapter(c)}><span>{String(c.number).padStart(2,'0')}</span><em>{c.title}</em></button>)}</aside>
      <article className="paperEditor"><div className="paperInner"><input className="chapterTitleInput" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Tên chương"/><div className="writingRule"/><textarea id="story-writing-area" spellCheck="true" className="writingArea" style={{fontFamily:font,fontSize:size,lineHeight:1.85}} value={content} onChange={e=>setContent(e.target.value)} placeholder="Bắt đầu viết chương của bạn…"/></div></article>
      {showAI?<InlineAI story={story} chapter={{...chapter,title,content}} user={null} notify={notify} onInsert={(text)=>{setContent(c=>(c?c+'\n\n':'')+text);setShowAI(true);notify('Đã chèn nội dung AI vào cuối bản thảo hiện tại.')}}/>:<aside className="editorSide"><div className="sideCard"><span className="eyebrow">CHƯƠNG HIỆN TẠI</span><h3>{title||chapter.title}</h3><div className="metric"><span>Từ</span><b>{words(content).toLocaleString('vi-VN')}</b></div><div className="metric"><span>Ký tự</span><b>{chars(content).toLocaleString('vi-VN')}</b></div><button className="aiLaunch" onClick={()=>setShowAI(true)}>✦ Hội ý AI</button></div><div className="sideCard"><span className="eyebrow">ĐIỀU HƯỚNG</span><div className="prevNext"><button disabled={chapters.findIndex(c=>c.id===chapter.id)===0} onClick={goPrev}>← Trước</button><button disabled={chapters.findIndex(c=>c.id===chapter.id)===chapters.length-1} onClick={goNext}>Sau →</button></div></div></aside>}
    </div>{showVersions&&<VersionModal versions={versions} onClose={()=>setShowVersions(false)} onRestore={restore}/>}</div>
}

function InlineAI({story,chapter,notify,onInsert}){
  const [mode,setMode]=useState('continue'),[length,setLength]=useState('1500-2000'),[tone,setTone]=useState('Tự nhiên, điện ảnh'),[prompt,setPrompt]=useState(''),[result,setResult]=useState(''),[loading,setLoading]=useState(false);
  const labels={continue:'Viết tiếp',plot:'Gợi ý diễn biến',dialogue:'Gợi ý lời thoại',logic:'Kiểm tra logic'};
  const context=async()=>{const out={};for(const t of ['characters','world_entries','timeline_events','canon_items','notes']){const r=await supabase.from(t).select('*').eq('story_id',story.id).limit(t==='canon_items'?100:80);out[t]=r.data||[]}return out};
  const run=async()=>{setLoading(true);setResult('');try{const ctx=await context();let req='';if(mode==='continue')req=`Viết tiếp trực tiếp từ cuối chương hiện tại. Mục tiêu ${length} từ. Phong cách: ${tone}. Không tóm tắt phần trước, không tự thêm nhân vật quan trọng nếu chưa có căn cứ. ${prompt}`;if(mode==='plot')req=`Đề xuất 4 hướng diễn biến tiếp theo. Với mỗi hướng: ý tưởng, lợi ích, rủi ro, ảnh hưởng Canon. Chưa viết thành chương. ${prompt}`;if(mode==='dialogue')req=`Viết mẫu lời thoại cho cảnh hiện tại. Giữ đúng tính cách, quan hệ, địa vị và bối cảnh. ${prompt}`;if(mode==='logic')req=`Kiểm tra logic truyện và chương hiện tại. Chia thành lỗi chắc chắn, điểm cần làm rõ, rủi ro tương lai, đề xuất xử lý. Không tự sửa bản thảo. ${prompt}`;const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,prompt:req,story,chapter,context:ctx,selection:chapter.content||''})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI không phản hồi.');setResult(d.text||'AI không trả về nội dung.')}catch(e){notify(e.message)}finally{setLoading(false)}};
  return <aside className="inlineAI"><div className="inlineAIHead"><div><span className="eyebrow">STORYFORGE AI</span><h3>Hội ý ngay trong chương</h3><p>AI đọc Canon, nhân vật, thế giới và timeline trước khi trả lời.</p></div></div><div className="inlineModes">{Object.entries(labels).map(([k,l])=><button key={k} className={mode===k?'active':''} onClick={()=>{setMode(k);setResult('')}}>{l}</button>)}</div><div className="inlineControls"><label>Độ dài<select value={length} onChange={e=>setLength(e.target.value)}><option value="300-500">300–500 từ</option><option value="800-1000">800–1.000 từ</option><option value="1500-2000">1.500–2.000 từ</option><option value="2000-3000">2.000–3.000 từ</option></select></label><label>Phong cách<select value={tone} onChange={e=>setTone(e.target.value)}><option>Tự nhiên, điện ảnh</option><option>Đời thường, tiết chế</option><option>Căng thẳng, bí ẩn</option><option>Nhanh, giàu hành động</option><option>Chậm, giàu cảm xúc</option></select></label></div><label>Yêu cầu thêm<textarea rows="3" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ví dụ: giữ nhịp chậm, không thêm nhân vật mới…"/></label><div className="inlineResult">{loading?<div className="aiLoading"><div className="aiSpinner">✦</div><h3>AI đang đọc ngữ cảnh…</h3><p>Đối chiếu Canon · nhân vật · thế giới · timeline.</p></div>:result?<textarea className="aiResultText" value={result} onChange={e=>setResult(e.target.value)}/>:<div className="aiEmpty"><div className="aiRobot">✦</div><h3>{labels[mode]}</h3><p>{mode==='continue'?'Viết tiếp từ chương đang mở.':mode==='plot'?'Đưa ra hướng đi để bạn chọn.':mode==='dialogue'?'Đề xuất lời thoại đúng nhân vật.':'Tìm mâu thuẫn trước khi thành lỗi truyện.'}</p></div>}</div><div className="inlineActions"><button className="ghost" onClick={()=>setResult('')}>Xóa</button>{result&&<button className="soft" onClick={()=>onInsert(result)}>✦ Chèn tại cuối bản thảo</button>}<button className="primary" disabled={loading} onClick={run}>{loading?'Đang tạo…':'✦ '+labels[mode]}</button></div></aside>}

function VersionModal({versions,onClose,onRestore}){return <SimpleModal title="Lịch sử phiên bản" onClose={onClose}><div className="versionList">{!versions.length?<div className="empty">Chưa có phiên bản lưu.</div>:versions.map(v=><div className="versionRow" key={v.id}><div><b>{v.title||'Không tên'}</b><small>{fmt(v.created_at)} · {v.word_count||0} từ</small></div><button className="ghost small" onClick={()=>onRestore(v)}>Khôi phục</button></div>)}</div></SimpleModal>}
function ChapterForm({onSave,onCancel}){const [title,setTitle]=useState('');return <><label>Tên chương<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Căn nhà cuối hẻm"/></label><div className="modalActions"><button className="ghost" onClick={onCancel}>Hủy</button><button className="primary" onClick={()=>onSave({title})}>Tạo chương</button></div></>}

const configs={
 characters:{table:'characters',singular:'nhân vật',title:'Nhân vật',desc:'Hồ sơ nhân vật để AI và chính bạn không quên những điều quan trọng.',fields:[['name','Tên'],['role','Vai trò'],['age','Tuổi'],['personality','Tính cách'],['appearance','Ngoại hình'],['relationships','Quan hệ'],['notes','Ghi chú']]},
 world:{table:'world_entries',singular:'mục thế giới',title:'Thế giới',desc:'Địa điểm, tổ chức, quy luật và nền tảng của thế giới truyện.',fields:[['name','Tên'],['category','Phân loại'],['description','Mô tả'],['rules','Quy tắc'],['notes','Ghi chú']]},
 timeline:{table:'timeline_events',singular:'sự kiện',title:'Dòng thời gian',desc:'Giữ thứ tự sự kiện để truyện không tự mâu thuẫn.',fields:[['date_label','Mốc thời gian'],['title','Tên sự kiện'],['description','Mô tả'],['characters','Nhân vật liên quan'],['sort_order','Thứ tự']]},
 canon:{table:'canon_items',singular:'luật Canon',title:'Canon',desc:'Những điều đã chốt. AI phải ưu tiên khu vực này trước khi đề xuất.',fields:[['key','Khóa Canon'],['value','Giá trị'],['source','Nguồn / lý do'],['locked','Khóa Canon']]},
 notes:{table:'notes',singular:'ghi chú',title:'Ghi chú',desc:'Ý tưởng, việc cần làm và những điều chưa muốn đưa vào Canon.',fields:[['title','Tiêu đề'],['category','Phân loại'],['status','Trạng thái'],['content','Nội dung']]}
};
function DataModule({story,type,notify}){
  const cfg=configs[type], [items,setItems]=useState([]),[form,setForm]=useState(null),[q,setQ]=useState(''),[busy,setBusy]=useState(false);
  const load=async()=>{if(!story){setItems([]);return}let query=supabase.from(cfg.table).select('*').eq('story_id',story.id);if(type==='timeline')query=query.order('sort_order',{ascending:true}).order('created_at',{ascending:true});else query=query.order('updated_at',{ascending:false});const r=await query;if(!r.error)setItems(r.data||[]);else notify(r.error.message)};
  useEffect(()=>{load()},[story?.id,type]);
  if(!story)return <EmptySelect title={`Chọn truyện để mở ${cfg.title.toLowerCase()}`} text="Các dữ liệu này thuộc riêng từng truyện."/>;
  const filtered=items.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));
  const blank=Object.fromEntries(cfg.fields.map(([k])=>[k,k==='locked'?true:k==='status'?'Inbox':'']));
  const saveItem=async f=>{setBusy(true);const payload={...f,story_id:story.id};if(type==='timeline'&&payload.sort_order==='')payload.sort_order=items.length;let r;if(f.id)r=await supabase.from(cfg.table).update(payload).eq('id',f.id).select().single();else r=await supabase.from(cfg.table).insert(payload).select().single();setBusy(false);if(r.error)return notify(r.error.message);setForm(null);await load();notify(f.id?'Đã cập nhật.':'Đã thêm.')};
  const remove=async id=>{if(!confirm('Xóa mục này?'))return;const r=await supabase.from(cfg.table).delete().eq('id',id);if(r.error)return notify(r.error.message);setItems(x=>x.filter(a=>a.id!==id));notify('Đã xóa.')};
  return <section><div className="sectionHead"><div><span className="eyebrow">{story.title}</span><h2>{cfg.title}</h2><p className="muted">{cfg.desc}</p></div><button className="primary" onClick={()=>setForm(blank)}>＋ Thêm {cfg.singular}</button></div><div className="moduleToolbar"><div className="searchBox">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Tìm ${cfg.singular}…`}/></div><span className="count">{filtered.length} mục</span></div>
    {!filtered.length?<div className="empty big"><div className="emptyArt">{icons[type]}</div><h3>Chưa có {cfg.title.toLowerCase()}</h3><p>Thêm dữ liệu để StoryForge xây dựng bộ nhớ cho truyện.</p><button className="primary" onClick={()=>setForm(blank)}>＋ Thêm mới</button></div>:<div className={'dataGrid '+type}>{filtered.map(x=><article className="dataCard" key={x.id}><div className="dataCardTop"><span className="tag">{type==='characters'?x.role||'Nhân vật':type==='world'?x.category||'Thế giới':type==='timeline'?x.date_label||'Mốc':type==='canon'?'CANON':'NOTE'}</span>{type==='canon'&&<span className="lock">{x.locked?'🔒':'○'}</span>}</div><h3>{x.name||x.title||x.key}</h3><p>{short(x.description||x.content||x.value||x.personality||'Chưa có mô tả.',180)}</p><div className="dataMeta">Cập nhật {fmt(x.updated_at||x.created_at)}</div><div className="cardActions"><button onClick={()=>setForm(x)}>Sửa</button><button className="iconBtn danger" onClick={()=>remove(x.id)}>×</button></div></article>)}</div>}
    {form&&<DataModal cfg={cfg} data={form} busy={busy} onClose={()=>setForm(null)} onSave={saveItem}/>}</section>
}
function DataModal({cfg,data,busy,onClose,onSave}){const [f,setF]=useState({...data});return <SimpleModal title={data.id?`Sửa ${cfg.singular}`:`Thêm ${cfg.singular}`} onClose={onClose}><div className="formGrid">{cfg.fields.map(([k,l])=>k==='locked'?<label className="checkLabel" key={k}><input type="checkbox" checked={!!f[k]} onChange={e=>setF({...f,[k]:e.target.checked})}/><span>🔒 {l}</span></label>:k==='status'?<label key={k}>{l}<select value={f[k]||'Inbox'} onChange={e=>setF({...f,[k]:e.target.value})}><option>Inbox</option><option>Đang xử lý</option><option>Đã xử lý</option><option>Đưa vào Canon</option></select></label>:k==='category'?<label key={k}>{l}<input value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/></label>:<label key={k}>{l}{['name','title','key','age','role','date_label','sort_order'].includes(k)?<input value={f[k]??''} onChange={e=>setF({...f,[k]:e.target.value})}/>:<textarea rows={k==='value'||k==='content'||k==='description'?6:4} value={f[k]??''} onChange={e=>setF({...f,[k]:e.target.value})}/>}</label>)}</div><div className="modalActions"><button className="ghost" onClick={onClose}>Hủy</button><button className="primary" disabled={busy} onClick={()=>onSave(f)}>{busy?'Đang lưu…':'Lưu'}</button></div></SimpleModal>}

function AIHub({story,chapter,user,notify}){
  const [mode,setMode]=useState('continue'),[length,setLength]=useState('1500-2000'),[tone,setTone]=useState('Tự nhiên, điện ảnh'),[prompt,setPrompt]=useState(''),[result,setResult]=useState(''),[loading,setLoading]=useState(false),[history,setHistory]=useState([]),[selected,setSelected]=useState(null),[showFullHistory,setShowFullHistory]=useState(false);
  const labels={continue:'Viết tiếp',plot:'Gợi ý diễn biến',dialogue:'Gợi ý lời thoại',logic:'Kiểm tra logic'};
  const loadHistory=async()=>{let h=[];const r=await supabase.from('ai_conversations').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(showFullHistory?100:12);if(!r.error)h=r.data||[];if(!h.length)h=load('ai_history_'+user.id,[]);setHistory(h)};
  useEffect(()=>{loadHistory()},[user.id,showFullHistory]);
  const context=async()=>{if(!story)return{};const out={};for(const t of ['characters','world_entries','timeline_events','canon_items','notes']){const r=await supabase.from(t).select('*').eq('story_id',story.id).limit(t==='canon_items'?100:80);out[t]=r.data||[]}return out};
  const run=async()=>{if(!story)return notify('Hãy chọn một truyện trước.');if(mode==='continue'&&!chapter)return notify('Hãy mở một chương trước khi dùng Viết tiếp.');setLoading(true);setResult('');try{const ctx=await context();let req='';if(mode==='continue')req=`Viết tiếp trực tiếp từ cuối chương hiện tại. Mục tiêu ${length} từ. Phong cách: ${tone}. Không tóm tắt phần trước, không tự thêm nhân vật quan trọng nếu chưa có căn cứ. ${prompt}`;if(mode==='plot')req=`Đề xuất 4 hướng diễn biến tiếp theo. Với mỗi hướng: ý tưởng, lợi ích, rủi ro, ảnh hưởng Canon. Chưa viết thành chương. ${prompt}`;if(mode==='dialogue')req=`Viết mẫu lời thoại cho cảnh hiện tại. Giữ đúng tính cách, quan hệ, địa vị và bối cảnh. Có thể kèm chỉ dẫn ngắn về sắc thái. ${prompt}`;if(mode==='logic')req=`Kiểm tra logic của truyện và chương hiện tại. Chia thành: lỗi chắc chắn, điểm cần làm rõ, rủi ro tương lai, đề xuất xử lý. Không tự sửa bản thảo. ${prompt}`;
      const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,prompt:req,story,chapter,context:ctx,selection:chapter?.content||''})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI không phản hồi.');const text=d.text||'AI không trả về nội dung.';setResult(text);const item={id:crypto.randomUUID(),user_id:user.id,story_id:story.id,chapter_id:chapter?.id||null,mode,prompt:req,result:text,created_at:new Date().toISOString(),storyTitle:story.title,chapterTitle:chapter?.title};await supabase.from('ai_conversations').insert({user_id:user.id,story_id:story.id,chapter_id:chapter?.id||null,mode,prompt:req,result:text});const old=load('ai_history_'+user.id,[]);save('ai_history_'+user.id,[item,...old].slice(0,50));setHistory(h=>[item,...h].slice(0,100));
    }catch(e){notify(e.message)}finally{setLoading(false)}};
  const insert=async()=>{if(!result||!chapter)return notify('Chưa có kết quả để chèn.');await supabase.from('chapter_versions').insert({chapter_id:chapter.id,title:chapter.title,content:chapter.content||'',word_count:words(chapter.content||'')});const next=(chapter.content?chapter.content+'\n\n':'')+result;const r=await supabase.from('chapters').update({content:next,word_count:words(next)}).eq('id',chapter.id).select().single();if(r.error)return notify(r.error.message);notify('Đã chèn vào bản thảo và lưu phiên bản cũ.');};
  if(!story)return <EmptySelect title="Trợ lý AI đang chờ một truyện" text="Chọn truyện rồi mở AI để viết tiếp, brainstorm, làm lời thoại hoặc kiểm tra logic."/>;
  return <section className="aiPage"><div className="aiHeader"><div><span className="eyebrow">STORYFORGE AI</span><h2>Hội ý với AI,<br/><em>quyền quyết định vẫn ở bạn.</em></h2><p>AI đọc Canon, nhân vật, thế giới, timeline và chương hiện tại trước khi trả lời.</p></div><div className="aiOrb">✦</div></div>
    <div className="aiModeBar">{Object.entries(labels).map(([k,l])=><button key={k} className={mode===k?'active':''} onClick={()=>{setMode(k);setResult('')}}>{k==='continue'?'↗':k==='plot'?'◈':k==='dialogue'?'“”':'✓'} {l}</button>)}</div>
    <div className="aiControls"><label>Độ dài<select value={length} onChange={e=>setLength(e.target.value)}><option value="300-500">300–500 từ</option><option value="800-1000">800–1.000 từ</option><option value="1500-2000">1.500–2.000 từ</option><option value="2000-3000">2.000–3.000 từ</option><option value="tùy chỉnh">Theo yêu cầu</option></select></label><label>Phong cách<select value={tone} onChange={e=>setTone(e.target.value)}><option>Tự nhiên, điện ảnh</option><option>Đời thường, tiết chế</option><option>Căng thẳng, bí ẩn</option><option>Nhanh, giàu hành động</option><option>Chậm, giàu cảm xúc</option></select></label><div className="aiContext"><span>Truyện: <b>{story.title}</b></span><span>Chương: <b>{chapter?.title||'Chưa chọn'}</b></span></div></div>
    <div className="aiGrid"><div className="aiMain"><div className="resultPanel">{loading?<div className="aiLoading"><div className="aiSpinner">✦</div><h3>AI đang đọc ngữ cảnh…</h3><p>Đối chiếu Canon · nhân vật · thế giới · timeline.</p></div>:result?<><div className="resultHead"><span className="tag">{labels[mode]}</span><span>Bản nháp / kết quả hội ý</span></div><textarea className="aiResultText" value={result} onChange={e=>setResult(e.target.value)}/></>:<div className="aiEmpty"><div className="aiRobot">✦</div><h3>{labels[mode]}</h3><p>{mode==='continue'?'Viết tiếp trực tiếp từ chương hiện tại.':mode==='plot'?'Nhận nhiều hướng trước khi quyết định.':mode==='dialogue'?'Lời thoại bám tính cách nhân vật.':'Tìm mâu thuẫn trước khi chúng thành lỗi truyện.'}</p></div>}</div><label className="promptLabel">Yêu cầu riêng<textarea rows="3" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ví dụ: giữ bí mật này, không thêm nhân vật mới, nhịp chậm…"/></label><div className="aiActions"><span>🔒 AI không tự sửa Canon hoặc bản thảo.</span><div><button className="ghost" onClick={()=>{setResult('');setPrompt('')}}>Xóa</button>{result&&mode==='continue'&&<button className="soft" onClick={insert}>＋ Chèn vào bản thảo</button>}<button className="primary" disabled={loading} onClick={run}>{loading?'Đang xử lý…':'✦ '+labels[mode]}</button></div></div></div>
      <aside className="aiHistory"><div className="panelHead"><div><span className="eyebrow">HISTORY</span><h3>Hội ý gần đây</h3></div><button className="linkBtn" onClick={loadHistory}>↻</button></div>{!history.length?<p className="muted">Chưa có hội ý.</p>:history.map(h=><button className={'historyItem '+(selected?.id===h.id?'selected':'')} key={h.id} onClick={()=>{setSelected(h);setResult(h.result||'');setMode(h.mode||'continue')}}><b>{labels[h.mode]||'Hội ý'}</b><small>{h.storyTitle||story.title}{h.chapterTitle?' · '+h.chapterTitle:''}</small><small>{fmt(h.created_at)}</small></button>)}<button className="linkBtn historyMore" onClick={()=>setShowFullHistory(!showFullHistory)}>{showFullHistory?'Thu gọn':'Xem nhiều hơn'}</button></aside></div>
  </section>
}

function Admin({notify}){const[users,setUsers]=useState([]),[filter,setFilter]=useState('pending'),[q,setQ]=useState(''),[loading,setLoading]=useState(false);const load=async()=>{setLoading(true);const r=await supabase.rpc('admin_list_users');setLoading(false);if(r.error)return notify('Không tải được thành viên: '+r.error.message);setUsers(r.data||[])};useEffect(()=>{load()},[]);const counts=useMemo(()=>({pending:users.filter(x=>x.status==='pending').length,approved:users.filter(x=>x.status==='approved').length,rejected:users.filter(x=>x.status==='rejected').length}),[users]);const act=async(u,status)=>{const r=await supabase.rpc('admin_set_user_status',{target_id:u.id,new_status:status});if(r.error)return notify(r.error.message);await load();notify(status==='approved'?'Đã duyệt thành viên.':'Đã từ chối thành viên.')};const shown=users.filter(x=>(filter==='all'||x.status===filter)&&JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));return <section><div className="adminHero"><div><span className="eyebrow">ADMIN CONTROL CENTER</span><h2>Thành viên</h2><p className="muted">Quản lý toàn bộ yêu cầu đăng ký và trạng thái truy cập.</p></div><button className="ghost" onClick={load}>↻ Làm mới</button></div><div className="adminStats">{[['pending','Chờ duyệt'],['approved','Đã duyệt'],['rejected','Từ chối'],['all','Tất cả']].map(([k,l])=><button className={filter===k?'selected':''} key={k} onClick={()=>setFilter(k)}><b>{k==='all'?users.length:counts[k]}</b><span>{l}</span></button>)}</div><div className="moduleToolbar"><div className="searchBox">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên hoặc email…"/></div></div>{loading?<div className="empty">Đang tải thành viên…</div>:!shown.length?<div className="empty big"><div className="emptyArt">✓</div><h3>Không có thành viên ở mục này.</h3><p>Khi có đăng ký mới, tài khoản sẽ xuất hiện tại đây.</p></div>:<div className="memberList">{shown.map(u=><div className="memberRow" key={u.id}><div className="memberIdentity"><div className="avatar">{(u.display_name||'U').slice(0,1).toUpperCase()}</div><div><b>{u.display_name||'User'}</b><small>{u.email}</small><small>Đăng ký: {fmt(u.created_at)}</small></div></div><div className="memberActions"><span className={'statusPill '+u.status}>{u.status==='pending'?'Chờ duyệt':u.status==='approved'?'Đã duyệt':'Từ chối'}</span>{!u.is_admin&&<>{u.status!=='approved'&&<button className="primary small" onClick={()=>act(u,'approved')}>✓ Duyệt</button>}{u.status!=='rejected'&&<button className="ghost small dangerText" onClick={()=>act(u,'rejected')}>Từ chối</button>}</>}</div></div>)}</div>}</section>}

function StoryModal({title,initial,onClose,onSave}){const[f,setF]=useState({title:initial?.title||'',genre:initial?.genre||'Quỷ dị',description:initial?.description||'',cover_url:initial?.cover_url||'',status:initial?.status||'writing'});return <SimpleModal title={title} onClose={onClose}><div className="coverPreview" style={f.cover_url?{backgroundImage:`linear-gradient(180deg,transparent,rgba(4,4,10,.9)),url(${f.cover_url})`}:undefined}>{!f.cover_url&&<span>✦</span>}<div><b>{f.title||'Tên truyện'}</b><small>{f.genre}</small></div></div><label>Tên truyện<input autoFocus value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="Việt Nam Quỷ Dị"/></label><div className="formGrid two"><label>Thể loại<select value={f.genre} onChange={e=>setF({...f,genre:e.target.value})}><option>Quỷ dị</option><option>Trinh thám</option><option>Võ thuật</option><option>Giả tưởng</option><option>Khoa học viễn tưởng</option><option>Khác</option></select></label>{initial&&<label>Trạng thái<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="writing">Đang viết</option><option value="paused">Tạm dừng</option><option value="completed">Hoàn thành</option></select></label>}</div><label>Ảnh bìa <span className="muted">(link ảnh)</span><input value={f.cover_url} onChange={e=>setF({...f,cover_url:e.target.value})} placeholder="https://…"/></label><label>Mô tả<textarea rows="6" value={f.description} onChange={e=>setF({...f,description:e.target.value})} placeholder="Bối cảnh, hướng đi, điều quan trọng cần nhớ…"/></label><div className="modalActions"><button className="ghost" onClick={onClose}>Hủy</button><button className="primary" onClick={()=>{if(!f.title.trim())return alert('Hãy nhập tên truyện.');onSave(f)}}>{initial?'Lưu thay đổi':'Tạo truyện'}</button></div></SimpleModal>}
function SimpleModal({title,onClose,children}){return <div className="modalBack" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modalHead"><div><span className="eyebrow">STORYFORGE</span><h2>{title}</h2></div><button className="iconBtn" onClick={onClose}>×</button></div>{children}</div></div>}
function EmptySelect({title,text}){return <div className="empty big"><div className="emptyArt">✦</div><h3>{title}</h3><p>{text}</p></div>}

createRoot(document.getElementById('root')).render(<App/>);
